"""remove size from chunks table

Revision ID: 08d9682560d2
Revises: 234b8a286331
Create Date: 2024-12-21 17:43:40.677737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d9682560d2'
down_revision: Union[str, None] = '234b8a286331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
